version: '3'

services:
  ghost:
    image: ghost:3.7.0
    container_name: ghost
    volumes:
      - ./..:/var/lib/ghost/content/themes/liebling
      - ./ghost.db:/var/lib/ghost/content/data/ghost.db
    environment:
      - NODE_ENV=development
    ports:
      - 2368:2368
